version: '2'
services:
  provider:
    build:
      context: containers/provider
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    depends_on:
      - db
    volumes:
      - .:/app
    links:
      - db
    ports:
      - 3333:3333
    environment:
      e-auth_http__settings__env: development
      e-auth_db__uri: mongodb://db:27017/e-auth
      e-auth_accounts__uri: mongodb://db:27017/e-users
  db:
    build:
      context: containers/db
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    volumes:
      - .docker/db/data:/data/db
    ports:
      - 27017:27017
